name: MacOS
on: 
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        qt_ver: [5.13.0]
        qt_arch: [clang_64]
    env:
      targetName: HelloActions-Qt
    steps:
      # macos 11.0 默认环境变了,要指定
      - name: prepare env
        if: ${{ matrix.os == 'macos-11.0' }}
        run: |
          softwareupdate --all --install --force
          sudo xcode-select --print-path
          sudo xcode-select --switch /Library/Developer/CommandLineTools       
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          git clone https://github.com/qt-labs/qthttpserver.git --branch 5.15
          cd qthttpserver
          git clone https://gitclone.com/github.com/nodejs/http-parser
          mv http-parser/ ./src/3rdparty/
          qmake
          make -j2
          make install
          cd ..
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install zbar qrencode boost openssl@1.1 zlib pcre
          brew install grpc --HEAD
          git clone https://github.com/elrinor/qntp.git
          cd qntp
          touch qntp.pri
          cd ..
          mv qntp/ ./src/
          
          git clone https://github.com/Qv2ray/shadowsocksr-uvw.git
          cd shadowsocksr-uvw
          touch Shadowsocksr-uvw.pri
          cd ..
          mv shadowsocksr-uvw/ ./src/
          mv qthttpserver qhttpserver
          cd qhttpserver
          touch qhttpserver.pri
          cd ..
          mkdir 3rd
          mv qhttpserver/ ./3rd/
          qmake
          make -j2
      # 打包
      - name: package
        run: |
          # 拷贝依赖
          macdeployqt bin/release/${targetName}.app -qmldir=. -verbose=1 -dmg
      # 上传artifacts          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.targetName }}_${{ matrix.os }}_${{matrix.qt_ver}}.zip
          path: bin/release/${{ env.targetName }}.app
      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/release/${{ env.targetName }}.dmg
          asset_name: ${{ env.targetName }}_${{ matrix.os }}_${{ matrix.qt_ver }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
